
import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Authorisation extends javax.swing.JFrame {
 Connection con=null;
 PreparedStatement pst=null;
    /**
     * Creates new form Driver_Portal
     */
    public Authorisation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        pword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cpwordLabel = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        PwordLabel = new javax.swing.JLabel();
        Sname = new javax.swing.JTextField();
        FnameLabel = new javax.swing.JLabel();
        SnameLabel = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        mistakelabel = new javax.swing.JLabel();
        Pword = new javax.swing.JPasswordField();
        CPword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\super\\Desktop\\admin.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Driver Portal Member Login");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("UserName:");

        btnLogin.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pword, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGap(17, 17, 17))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(pword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 250, 520);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sign Up");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 70, 300, 50);

        mobile.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        mobile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        jPanel1.add(mobile);
        mobile.setBounds(280, 430, 320, 40);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Surname:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 220, 100, 40);

        cpwordLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cpwordLabel.setForeground(new java.awt.Color(102, 102, 102));
        cpwordLabel.setText("Confirm Password:");
        jPanel1.add(cpwordLabel);
        cpwordLabel.setBounds(450, 290, 190, 40);

        Fname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });
        jPanel1.add(Fname);
        Fname.setBounds(280, 180, 310, 40);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("First Name:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(270, 140, 100, 40);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Mobile Number:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(280, 390, 130, 40);

        btnRegister.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.setBorder(null);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister);
        btnRegister.setBounds(550, 480, 80, 40);

        btnCancel.setBackground(new java.awt.Color(0, 51, 255));
        btnCancel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setLabel("X");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);
        btnCancel.setBounds(560, 0, 70, 50);

        PwordLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        PwordLabel.setForeground(new java.awt.Color(102, 102, 102));
        PwordLabel.setText("Password");
        jPanel1.add(PwordLabel);
        PwordLabel.setBounds(280, 290, 100, 40);

        Sname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Sname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnameActionPerformed(evt);
            }
        });
        jPanel1.add(Sname);
        Sname.setBounds(280, 260, 320, 40);

        FnameLabel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(FnameLabel);
        FnameLabel.setBounds(380, 150, 200, 20);

        SnameLabel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(SnameLabel);
        SnameLabel.setBounds(380, 234, 220, 20);

        mobileLabel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(mobileLabel);
        mobileLabel.setBounds(420, 400, 220, 20);

        mistakelabel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(mistakelabel);
        mistakelabel.setBounds(280, 480, 250, 20);

        Pword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PwordActionPerformed(evt);
            }
        });
        jPanel1.add(Pword);
        Pword.setBounds(280, 330, 120, 40);
        jPanel1.add(CPword);
        CPword.setBounds(450, 330, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(645, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        try{
            String sql="INSERT INTO user(firstName,Surname,password,mobile) VALUES(?,?,?,?)";
            con=DriverManager.getConnection("jdbc:mysql://localhost/Driver_Portal","root","");
            pst=con.prepareStatement(sql);
            pst.setString(1,Fname.getText());
            pst.setString(2,Sname.getText());
            pst.setString(3,Pword.getText());
            pst.setString(4,mobile.getText());
            int mistake=0;
            if("".equals(Fname.getText())) {
                FnameLabel.setText("You are Required to Fill Your First Name");
                ++mistake;
            }
           else if(!"".equals(Fname.getText())){FnameLabel.setText(""); if(mistake>=1){--mistake;};}
             if("".equals(Sname.getText())){SnameLabel.setText("You are Required to Fill Your Surname"); ++mistake;}
             else if(!"".equals(Sname.getText())){SnameLabel.setText("");  if(mistake>=1){--mistake;};}
            if("".equals(mobile.getText())){mobileLabel.setText("You are Required to Fill Your Mobile Number");++mistake; }
            else if(!"".equals(mobile.getText())){mobileLabel.setText(""); if(mistake>=1){--mistake;};}
            if("".equals(Pword.getText())){PwordLabel.setText("Password Required");++mistake;}
            else if(!"".equals(Pword.getText())){PwordLabel.setText("");--mistake;}
            if(!Pword.getText().equals(CPword.getText())){cpwordLabel.setText("Password not Matching");++mistake;}
            else if(Pword.getText().equals(CPword.getText())){cpwordLabel.setText("");if(mistake>=1){--mistake;};}
             if(mistake>=1)
             {
                 mistakelabel.setText("You have"+" "+mistake+" "+"Non Filled Space");
             }
             else{
                 mistakelabel.setText("");
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"REGISTERED SUCESSFULLY");
             }
             
            
        }
        catch(Exception ex){
         JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
     String query="SELECT * FROM drivers WHERE lastName= ? AND password= ?";
     try {
         con=DriverManager.getConnection("jdbc:mysql://localhost/Driver_Portal","root","");
         pst=con.prepareStatement(query);
         pst.setString(1, username.getText());
         pst.setString(2,pword.getText());
         ResultSet rs;
         rs=pst.executeQuery();
         if(rs.next())
         {
             Forms userlogin=new Forms();
             JOptionPane.showMessageDialog(null,"Login Succesfully");
             userlogin.setVisible(true);
         }
         else{
              JOptionPane.showMessageDialog(null,"UserName or Password is Wrong");
              username.setText("");
              pword.setText("");
         }
         
     } catch (Exception ex) {
          JOptionPane.showMessageDialog(null,ex);
       
     } 
     
    }//GEN-LAST:event_btnLoginActionPerformed

    private void SnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SnameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void PwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PwordActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authorisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authorisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authorisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authorisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authorisation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CPword;
    private javax.swing.JTextField Fname;
    private javax.swing.JLabel FnameLabel;
    private javax.swing.JPasswordField Pword;
    private javax.swing.JLabel PwordLabel;
    private javax.swing.JTextField Sname;
    private javax.swing.JLabel SnameLabel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel cpwordLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mistakelabel;
    private javax.swing.JTextField mobile;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField pword;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables


}
